logLevel = "DEBUG"

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[web]
address = ":8080"

# Connection to docker host system (docker.sock)
[docker]
domain = "localhost"
watch = true
exposedbydefault = true
