version: "3"

networks:
    nginx: 
      external: 
        name: nginx_webapps
    webapps:
      external: 
        name: traefik_webapps

services:
  traefik:
    image: traefik
{% if config.apps.traefik.restart %}
    restart: always
{% endif %}
    volumes:
      - {{ app_deploy_config_dir }}/traefik.yml:/etc/traefik/traefik.toml
      - {{ config.target.docker_sock }}:/var/run/docker.sock:ro
    networks:
        - nginx
        - webapps
    ports:
      - {{ config.apps.traefik.ui_port }}:8080
      - {{ config.apps.traefik.http_port }}:80
      - {{ config.apps.traefik.https_port }}:443
    labels:
      - "com.toubiweb.app=traefik"
    environment:
      TZ: Europe/Paris
{% if config.apps.traefik.nginx_proxy %}
      VIRTUAL_HOST: {{ config.apps.traefik.nginx_proxy }}
      VIRTUAL_PORT: 80
{% endif %}